name: Auto Click Streamlit

on:
  schedule:
    - cron: '30-59/5 11 * * *'  # 11点30分至11点59分，每5分钟一次
    - cron: '0-30/5 12 * * *'   # 12点00分至12点30分，每5分钟一次
    
    # 23:30-24:30（即00:30）期间，每5分钟运行一次
    - cron: '30-59/5 23 * * *'  # 23点30分至23点59分，每5分钟一次
    - cron: '0-30/5 0 * * *'    # 00点00分至00点30分，每5分钟一次
  workflow_dispatch:           # 支持手动运行

jobs:
  clicker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # 使用自定义 token 方式推送

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install selenium webdriver-manager

    - name: Run auto click script
      run: python auto_click.py

    - name: Commit log file to repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # 如果日志文件不存在，说明是第一次运行，先创建
        if [ ! -f click_log.txt ]; then
          echo "初始化日志文件于 $(date +'%Y-%m-%d %H:%M:%S')" > click_log.txt
        fi

        git add click_log.txt

        # 提交并推送（如果有变更）
        if git diff --cached --quiet; then
          echo "无变化，无需提交"
        else
          git commit -m "更新日志: $(date +'%Y-%m-%d %H:%M:%S')"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
        fi
